name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 拉去代码
      - uses: actions/setup-node@v3 # 第三方
        with:
          node-version: 16
      - run: | # 多个需要竖线
          node -v
          npm -v
          npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.FRONT_END_NOTES_TOKEN }}
          publish_dir: ./dist
